"""change

Revision ID: 79e9e7f13dd1
Revises: 
Create Date: 2021-09-21 02:57:55.190738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79e9e7f13dd1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('info', 'student_name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('info', 'student_class',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('info', 'student_photo',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('info', 'student_photo',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('info', 'student_class',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('info', 'student_name',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
